#+TITLE: Wayland Notes
#+AUTHOR: David Conner
#+DESCRIPTION:
#+PROPERTY:
#+STARTUP: content
#+OPTIONS: toc:nil

* Table of Contents :TOC_3_gh:
- [[#wayland][Wayland]]
  - [[#wayland-overview-02][Wayland Overview]]
  - [[#pipewire][Pipewire]]
    - [[#removing-pipewirepulseaudio-packages][Removing Pipewire/Pulseaudio packages]]
    - [[#reinstalling-pipewire-packages][Reinstalling Pipewire Packages]]
    - [[#restarting-pipewirealsa-services][Restarting Pipewire/Alsa Services]]
    - [[#troubleshooting-alsa][Troubleshooting ALSA]]
    - [[#misc][Misc]]

* Wayland :wayland:

So I would like my Linux to be as close to full wayland as possible. I've only
run into a few problems so far, but there are probably many parts of my system
that need to be changed.

For now, I'm running on KDE, but I plan on switching to XMonad + KDE soon. Why
XMonad? KDE activities aren't well supported and are not likely to be in the
near future. I've only scraped the surface of Wayland/KDE and I'm not sure how
XMonad intersects with Wayland.


** TODO Wayland Overview [0/2] :wayland:
+ [ ] assess how close my system really is to 100% wayland
+ [ ]


** Pipewire

Pipewire plans on replacing PulseAudio in Wayland. This is where I've run into
the most problems so far.

*TLDR* if you've got pipewire and your audio isn't coming up after reboot,
chances are it's the packages/services/dependencies for ALSA and/or pipewire.
Occassionally a package may clobber your AUR dependencies and reinstall
PulseAudio.

*** Removing Pipewire/Pulseaudio packages

There are some problem packages on AUR which will sneakily riinstall
=pulseaudio= packages if you're not watching. In some cases, this forces you to
reinstall ALL =pipewire= dependent packages, which includes =kwin=, depending on
how deeply fucked your system is. Pamac and AUR are usually pretty good at
selecting the optional =pulseaudio=-providing packages, leaving your pipewire
intact. However, I've just reinstalled pipewire on my system for the third time,
twice on my MBP 2011 and now once on my MBP 2013.

Problem packages:
+ [[https://aur.archlinux.org/packages/fedora-firefox-wayland-bin/][fedora-firefox-wayland-bin]],
  - this has the optional dependency of pulseaudio, which should be provided by =pipewire-pulse=.
  - however, my system's audio was just hosed by this and i had to manually reinstall pipewire & alsa.
+ there are others...

The following removes most of the pipewire/pulse packages:

#+begin_src shell :tangle no
sudo pacman -Rns pulseeffects pipewire-pulse plasma-pa paprefs pavucontrol pavucontrol-qt
sudo pacman -Rns pulseaudio-alsa pulseaudio-ctl pulseaudio-equalizer-ladspa
sudo pacman -Rns pulseeffects pipewire-pulse plasma-pa paprefs pavucontrol pavucontrol-qt mkchromecast-git pipewire-support
#+end_src

Notes on reinstalling

+ avoid any install of pulseaudio like the plague
+ as long as pulseaudio is totally off your system,
  - then once pipewire-support is installed
  - the pulseaudio package is suppied by pipewire-pulse
  - pipewire-pulse then conflicts with pulseaudio
+ This may require restarting the system at various points, esp. if one wants to
  test whether the changes are permanent.

*** Reinstalling Pipewire Packages

**** Install the =pipewire-support= group

#+begin_src shell :tangle no
sudo pacman -Syu pipewire-support
sudo pacman -Syu plasma-pa
#+end_src

*** Restarting Pipewire/Alsa Services

**** Search for running pipewire/pulse services

#+begin_src shell :tangle no
systemctl --user list-units | grep pipewire
systemctl --user list-units | grep audio
systemctl --user list-units | grep pulse
#+end_src

**** Get status of =pipewire.service= and restart it

#+begin_src shell :tangle no
systemctl --user status pipewire.service
systemctl --user reload-or-restart pipewire.service
systemctl --user status pipewire.service
#+end_src

**** Look for pipewire services

#+begin_src shell :tangle no
systemctl --user list-units | grep pipe
systemctl --user status pipewire-pulse.socket
systemctl --user status pipewire-pulse.service
systemctl --user reload-or-restart pipewire-pulse.service
systemctl --user status pipewire-pulse.service
#+end_src


- I thought maybe the pipewire services were still down after boot, since the ALSA services fail to start during boot
  - but none of the pipewire services seem to list ALSA services as dependencies
  - this means pipewire is expecting to get information about audio hardware from another service/location, perhaps an intermediary service

**** Examine the Pipewire service dependencies

#+begin_src shell :tangle no
systemctl --user list-dependencies pipewire-media-session.service
#+end_src

#+begin_quote
pipewire-pulse.service
● ├─pipewire-pulse.socket
● ├─pipewire.service
● ├─session.slice
● └─basic.target
●   ├─paths.target
●   ├─sockets.target
●   │ ├─dbus.socket
●   │ ├─dirmngr.socket
●   │ ├─gpg-agent-browser.socket
●   │ ├─gpg-agent-extra.socket
●   │ ├─gpg-agent-ssh.socket
●   │ ├─gpg-agent.socket
●   │ ├─p11-kit-server.socket
●   │ └─pipewire.socket
●   └─timers.target
#+end_quote

*** Troubleshooting ALSA

**** These services are running under root, but failing during boot with commands like

#+begin_quote
/usr/bin/alsactl: state_lock:125: file /var/lib/alsa/asound.state lock error: File exists
/usr/bin/alsactl: load_state:1683: Cannot open /var/lib/alsa/asound.state for reading: File exists
alsa-lib parser.c:260:(error_node) UCM is not supported for this HDA model (HDA Intel PCH at 0xa0900000 irq 50)
alsa-lib main.c:1014:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -6
Found hardware: "HDA-Intel" "Cirrus Logic CS4206" "HDA:10134206,106b1c00,00100302 HDA:80862805,80860101,00100000" "0x8086" "0x7270"
Hardware is initialized using a generic method
#+end_quote

**** =alsa.state= or =alsa.restore= services: you typically only have one of these running.

Following a reinstall of the packages/services for ALSA and Pipewire, a manual
user action is required to get the Alsa services to restart.

Each is an alternative method of mediating access to ALSA hardware devices via
Linux. The idea behind forcing the user to choose which to use and requiring
user action to activate is that each method =alsa-state= and =alsa-restore= has
pro's and con's -- /which I can't recall, your honor/. Neither is perfect and the
user should be aware *at least once* of services interfacing with audio devices
on their system.

#+begin_src shell :tangle no
sudo systemctl list-dependencies alsa-state.service
sudo systemctl list-dependencies alsa-restore.service
#+end_src


**** useful links & tidbits for my chip: Cirrus Logic CS4206/4207

+ [[https://www.kernel.org/doc/html/latest/sound/hd-audio/models.html][Lists of audio hardware for laptops.]]
  - For me, I just needed to ctrl-f for =Cirrus= and/or =CS4206=
+ [[https://forum.garudalinux.org/t/soundcard-issues/3665/8][A useful Garuda Linux forum post on ALSA]]
+ [[https://wiki.archlinux.org/title/Advanced_Linux_Sound_Architecture#ALSA_and_Systemd][The ArchWiki post on ALSA and associated services]]
  - it mentions needing to choose between alsa-restore.service & alsa-state.service
+ alsa startup scripts mention UCM method being unavailable for my chip
  - SOF is a newer method, so probably unavailable too.
  - This was mostly a red herring for me. Goddammit Fred.

**** Troubleshooting modules/hardware access:

#+begin_quote
modinfo hdaudio:v10134206r\*a01\*
#+end_quote

**** Using =alsa-info.sh=

Found =alsa-info.sh=, which is mainly what the =alsa-utils= package provides

#+begin_src shell :tangle no
sudo pacman -Syu alsa-utils

# run this to follow the white rabbit
pacman -Fl alsa-utils | grep bin
#+end_src

When you run the script, you will be asked to update to 0.6.0, which will be downloaded to a temporary file. You'll need to replace it manually. Run it again.

#+begin_src shell :tangle no
/usr/bin/alsa-info.sh
#+end_src

*** Misc

**** Also strange are other services in the `journalctl -xb` logs which are showing problems

(pretty much just sudo, but what is home1.service?)

#+begin_quote
May 03 05:39:43 mbp2011 sudo[278758]: pam_systemd_home(sudo:account): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.

systemd-udevd[286]: controlC0: Process '/usr/bin/alsactl restore 0' failed with exit code 99.
#+end_quote
